"use client";

import { useEffect, useMemo, useState } from "react";
import {
  LayoutDashboard, Users, ScanLine, CreditCard, WalletCards, Dumbbell, CalendarDays, Wrench,
  Package, BarChart3, UserCog, Settings, Search, Bell, Menu, ChevronLeft, LogOut, Plus, X,
  UserPlus, Banknote, ReceiptText, CalendarPlus, Activity, CheckCircle2, Clock3, Star, ShoppingCart,
  AlertTriangle, Download, SlidersHorizontal, MoreHorizontal, QrCode, UserRoundSearch, Pencil, Snowflake,
  Send, TrendingUp, ShieldCheck, RotateCcw, Save, Eye, CircleDollarSign, Zap, ClipboardList
} from "lucide-react";
import {
  initialMembers, trainers, classes, initialEquipment, initialInventory, initialTransactions,
  initialCheckins, notifications as notificationSeed, plansData, staff, expenses
} from "./mockData";

const navItems = [
  ["dashboard", "Dashboard", LayoutDashboard], ["members", "Members", Users], ["checkin", "Check In", ScanLine],
  ["memberships", "Memberships", CreditCard], ["payments", "Payments", WalletCards], ["trainers", "Trainers", Dumbbell],
  ["classes", "Classes", CalendarDays], ["equipment", "Equipment", Wrench], ["inventory", "Inventory", Package],
  ["reports", "Reports", BarChart3], ["staff", "Staff", UserCog], ["settings", "Settings", Settings]
];
const titles = Object.fromEntries(navItems.map(([id, label]) => [id, label]));
const fmt = n => `${Number(n).toLocaleString()} ETB`;
const initials = name => name.split(" ").map(x => x[0]).join("");
const statusClass = s => `status ${String(s).toLowerCase().replace(" soon", "").replace("under ", "")}`;

function Stat({ label, value, note, muted }) {
  return <div className="card stat"><div className="label">{label}</div><div className="value">{value}</div><div className={`trend ${muted ? "muted" : ""}`}>{note}</div></div>;
}

function SectionHead({ title, sub, children }) {
  return <div className="section-head"><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{children}</div>;
}

function Bars({ values = [43, 52, 48, 67, 59, 76, 84], labels = ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"], compare }) {
  return <div className="chart">{values.map((v, i) => <div className="bar-wrap" key={labels[i]}>{compare && <i className="bar alt" style={{ height: `${Math.max(10, v - 15)}%` }} />}<i className="bar" style={{ height: `${v}%` }} /><span className="bar-label">{labels[i]}</span></div>)}</div>;
}

function MiniPerson({ name, sub }) {
  return <div className="person"><div className="mini-avatar">{initials(name)}</div><div><strong>{name}</strong>{sub && <span>{sub}</span>}</div></div>;
}

function Empty({ text = "No matching records found." }) { return <div className="empty">{text}</div>; }

function Field({ label, children }) { return <div className="field"><label>{label}</label>{children}</div>; }

function Modal({ modal, close, members, onAddMember, onPayment, onRenew, onGeneric }) {
  if (!modal) return null;
  const titlesMap = { member: "Register new member", payment: "Record payment", renew: "Renew membership", expense: "Add expense", class: "Create class", plan: "Create membership plan", staff: "Add staff member", issue: "Report equipment issue", session: "Add training session", trainer: "Assign trainer", booking: "Book member", edit: "Edit details" };
  const submit = e => {
    e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget));
    if (modal.type === "member") onAddMember(data); else if (modal.type === "payment") onPayment(data); else if (modal.type === "renew") onRenew(data); else onGeneric(titlesMap[modal.type] || "Update");
  };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><form className="modal" onSubmit={submit}>
    <div className="modal-head"><h2>{titlesMap[modal.type] || modal.title}</h2><button type="button" onClick={close} aria-label="Close"><X /></button></div>
    <div className="modal-body">
      {modal.type === "member" && <div className="form-grid">
        <Field label="First name"><input className="input" name="first" required /></Field><Field label="Last name"><input className="input" name="last" required /></Field>
        <Field label="Phone"><input className="input" name="phone" placeholder="+251 9…" required /></Field><Field label="Email"><input className="input" name="email" type="email" /></Field>
        <Field label="Gender"><select className="select" name="gender"><option>Female</option><option>Male</option></select></Field><Field label="Date of birth"><input className="input" name="dob" type="date" /></Field>
        <Field label="Address"><input className="input" name="address" placeholder="Addis Ababa" /></Field><Field label="Emergency contact"><input className="input" name="emergency" /></Field>
        <Field label="Membership plan"><select className="select" name="plan">{plansData.map(p => <option key={p.name}>{p.name}</option>)}</select></Field><Field label="Start date"><input className="input" name="start" type="date" defaultValue="2026-10-05" /></Field>
        <Field label="Assign trainer"><select className="select" name="trainer">{trainers.map(t => <option key={t.name}>{t.name}</option>)}</select></Field><Field label="Fitness goal"><select className="select" name="goal"><option>Weight Loss</option><option>Muscle Gain</option><option>General Fitness</option><option>Strength</option><option>Bodybuilding</option><option>Cardio</option></select></Field>
        <Field label="Initial weight (kg)"><input className="input" name="weight" type="number" /></Field><Field label="Height (cm)"><input className="input" name="height" type="number" /></Field>
        <Field label="Payment method"><select className="select" name="method"><option>Cash</option><option>Bank Transfer</option><option>Telebirr</option><option>Other</option></select></Field><Field label="Amount paid"><input className="input" name="amount" type="number" /></Field>
      </div>}
      {modal.type === "payment" && <div className="form-grid">
        <Field label="Select member"><select className="select" name="member" defaultValue={modal.member || "Sara Bekele"}>{members.map(m => <option key={m.id}>{m.name}</option>)}</select></Field>
        <Field label="Payment type"><select className="select" name="description"><option>Monthly Membership Renewal</option><option>Personal training session</option><option>Shop purchase</option><option>Outstanding balance</option></select></Field>
        <Field label="Amount"><input className="input" name="amount" type="number" defaultValue="2500" required /></Field><Field label="Payment method"><select className="select" name="method"><option>Cash</option><option>Telebirr</option><option>Bank Transfer</option><option>Other</option></select></Field>
        <Field label="Reference"><input className="input" name="reference" placeholder="Optional" /></Field><Field label="Notes"><input className="input" name="notes" placeholder="Optional" /></Field>
      </div>}
      {modal.type === "renew" && <div className="form-grid">
        <Field label="Member"><input className="input" value={modal.member || "Abel Tesfaye"} readOnly name="member" /></Field>
        <Field label="Membership plan"><select className="select" name="plan" defaultValue="Monthly"><option>Daily Pass</option><option>Monthly</option><option>3 Months</option><option>6 Months</option><option>Annual</option><option>Premium</option></select></Field>
        <Field label="Start date"><input className="input" name="start" type="date" defaultValue="2026-10-05" /></Field><Field label="Amount"><input className="input" name="amount" type="number" defaultValue="2500" /></Field>
        <Field label="Payment method"><select className="select" name="method"><option>Cash</option><option>Telebirr</option><option>Bank Transfer</option></select></Field><Field label="New expiry"><input className="input" value="November 5, 2026" readOnly /></Field>
      </div>}
      {!["member", "payment", "renew"].includes(modal.type) && <div className="form-grid">
        <Field label="Name / title"><input className="input" name="name" defaultValue={modal.subject || ""} required /></Field>
        <Field label={modal.type === "expense" ? "Amount (ETB)" : "Category"}><input className="input" name="detail" placeholder={modal.type === "expense" ? "4,500" : "Select or enter"} /></Field>
        <Field label="Date"><input className="input" type="date" defaultValue="2026-10-05" /></Field><Field label="Status"><select className="select"><option>Active</option><option>Scheduled</option><option>Pending</option></select></Field>
        <Field label="Notes"><textarea className="textarea" placeholder="Add relevant details" /></Field>
      </div>}
    </div>
    <div className="modal-foot"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn primary" type="submit"><Save /> Save changes</button></div>
  </form></div>;
}

function Dashboard({ inside, openModal, go }) {
  const activities = [["6:43 PM", "Abel Tesfaye checked in"], ["6:32 PM", "Sara Bekele renewed Gold membership"], ["6:15 PM", "Henok Girma completed a training session"], ["5:52 PM", "Payment of 2,500 ETB received"], ["5:40 PM", "Treadmill #07 reported for maintenance"]];
  const quick = [["Register Member", UserPlus, "member"], ["Check In Member", ScanLine, null], ["Record Payment", Banknote, "payment"], ["Create Membership", CreditCard, "plan"], ["Add Expense", ReceiptText, "expense"], ["Add Class", CalendarPlus, "class"]];
  return <>
    <div className="grid stats"><Stat label="Total members" value="842" note="+38 this month"/><Stat label="Active members" value="716" note="85% of all members"/><Stat label="Inside gym now" value={inside} note="Peak window starts at 5 PM"/><Stat label="Expiring this week" value="27" note="8 renewals pending" muted/><Stat label="Revenue this month" value="684,500 ETB" note="↑ 12.4% vs last month"/><Stat label="Today's check ins" value="314" note="+27 vs last Sunday"/><Stat label="New members" value="38" note="On pace for 46"/><Stat label="Outstanding" value="42,800 ETB" note="17 members" muted/></div>
    <div className="grid dashboard-body"><div>
      <SectionHead title="Performance overview" sub="Revenue and membership growth · Apr–Oct 2026" />
      <div className="grid chart-grid"><div className="card"><div className="label">Monthly revenue <span style={{color:"var(--lime)",float:"right"}}>684.5K ETB</span></div><Bars compare /></div><div className="card"><div className="label">Plan distribution</div><div className="donut-wrap"><div className="donut"/><div className="legend"><span><i style={{background:"var(--lime)"}}/>Monthly 42%</span><span><i style={{background:"var(--cyan)"}}/>3 Months 23%</span><span><i style={{background:"var(--amber)"}}/>Annual 17%</span><span><i style={{background:"#8b7bd8"}}/>Other 18%</span></div></div></div></div>
    </div><div><SectionHead title="Today's activity" sub="Live operations feed"/><div className="card activity">{activities.map(([time,text],i)=><div className="activity-row" key={text}><time>{time}</time><span className="activity-icon">{i === 4 ? <Wrench size={14}/> : <Activity size={14}/>}</span><p>{text}</p></div>)}</div></div></div>
    <SectionHead title="Quick actions" sub="Common front desk tasks" />
    <div className="grid quick">{quick.map(([label,Icon,type])=><button className="btn" key={label} onClick={()=>type ? openModal(type) : go("checkin")}><Icon/>{label}</button>)}</div>
  </>;
}

function MembersPage({ members, openMember, openModal }) {
  const [filter,setFilter]=useState("All"); const [q,setQ]=useState("");
  const shown=members.filter(m=>(filter==="All"||m.status===filter||(filter==="New Members"&&m.id>"AF-1050"))&&m.name.toLowerCase().includes(q.toLowerCase())).slice(0,12);
  return <><div className="toolbar"><input className="input" placeholder="Search by name, phone or ID" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn"><SlidersHorizontal/> Filters</button><span className="spacer"/><button className="btn primary" onClick={()=>openModal("member")}><Plus/> Add member</button></div><div className="filters" style={{marginBottom:15}}>{["All","Active","Expired","Expiring Soon","Frozen","New Members"].map(x=><button className={`filter ${filter===x?"active":""}`} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>
  <div className="table-wrap">{shown.length?<table className="table"><thead><tr><th>Member</th><th>Phone</th><th>Membership</th><th>Trainer</th><th>Join date</th><th>Expiration</th><th>Status</th><th>Last visit</th><th/></tr></thead><tbody>{shown.map(m=><tr key={m.id} onClick={()=>openMember(m)}><td><MiniPerson name={m.name} sub={m.id}/></td><td>{m.phone}</td><td>{m.plan}</td><td>{m.trainer}</td><td>{m.join}</td><td>{m.expiry}</td><td><span className={statusClass(m.status)}>{m.status}</span></td><td>{m.lastVisit}</td><td><button className="link">View</button></td></tr>)}</tbody></table>:<Empty/>}</div><div className="pagination"><span>Showing {shown.length} of {members.length} members</span><div className="pages"><button className="active">1</button><button>2</button><button>3</button></div></div></>;
}

function MemberProfile({ member, back, openModal, checkinMember }) {
  const [tab,setTab]=useState("Overview");
  const tabs=["Overview","Attendance","Payments","Measurements","Workout Plan","Notes"];
  return <><button className="btn ghost small" onClick={back}><ChevronLeft/> Back to members</button><div className="card profile-hero" style={{marginTop:14}}><div className="large-avatar">{initials(member.name)}</div><div><h2>{member.name}</h2><div className="profile-meta"><span>{member.id}</span><span>{member.phone}</span><span>{member.email}</span><span className={statusClass(member.status)}>{member.status}</span></div></div><div className="profile-actions"><button className="btn" onClick={()=>checkinMember(member)}><ScanLine/> Check in</button><button className="btn primary" onClick={()=>openModal("renew",member.name)}><CreditCard/> Renew membership</button><button className="btn" onClick={()=>openModal("payment",member.name)}><Banknote/> Record payment</button><button className="btn" onClick={()=>openModal("trainer",member.name)}>Assign trainer</button><button className="btn" onClick={()=>openModal("edit",member.name)}><Pencil/> Edit</button><button className="btn danger" onClick={()=>openModal("edit",member.name)}><Snowflake/> Freeze</button></div></div>
  <div className="tabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {tab==="Overview"?<><div className="grid visit-stats"><Stat label="Total visits" value={member.visits} note="Since joining" muted/><Stat label="Visits this month" value={member.monthVisits} note="+3 vs September"/><Stat label="Average / week" value="4.2" note="Top 22%"/><Stat label="Last visit" value="Today" note="6:42 PM" muted/></div><div className="grid detail-grid" style={{marginTop:16}}><div className="card detail-card"><h3>Personal information</h3><div className="info-list"><div><span>Gender</span><strong>{member.gender}</strong></div><div><span>Date of birth</span><strong>{member.dob}</strong></div><div><span>Emergency contact</span><strong>{member.emergency}</strong></div><div><span>Member since</span><strong>{member.join}</strong></div></div></div><div className="card detail-card"><h3>Membership information</h3><div className="info-list"><div><span>Plan</span><strong>{member.plan}</strong></div><div><span>Expires</span><strong style={{color:member.status==="Expiring Soon"?"var(--amber)":"inherit"}}>{member.expiry}</strong></div><div><span>Amount paid</span><strong>2,500 ETB</strong></div><div><span>Balance</span><strong>{fmt(member.balance)}</strong></div></div></div><div className="card detail-card"><h3>Fitness & trainer</h3><div className="info-list"><div><span>Trainer</span><strong>{member.trainer}</strong></div><div><span>Goal</span><strong>{member.goal}</strong></div><div><span>Weight / height</span><strong>{member.weight} kg · {member.height} cm</strong></div><div><span>BMI</span><strong>{(member.weight/(member.height/100)**2).toFixed(1)}</strong></div></div></div></div></>:<HistoryTab tab={tab} member={member}/>}</>;
}

function HistoryTab({tab,member}) {
  const rows = tab==="Payments" ? [["Oct 5, 2026","Monthly membership","2,500 ETB","Paid"],["Sep 5, 2026","Monthly membership","2,500 ETB","Paid"],["Aug 24, 2026","Personal training","900 ETB","Paid"]] : tab==="Attendance" ? [["Oct 5, 2026","6:42 PM","8:08 PM","1h 26m"],["Oct 3, 2026","6:18 PM","7:51 PM","1h 33m"],["Oct 1, 2026","7:04 PM","8:22 PM","1h 18m"]] : [["Oct 5, 2026",tab,member.goal,"Current"],["Sep 5, 2026",tab,"Progress updated","Complete"]];
  return <div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Record</th><th>Detail</th><th>Status</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===3?<span className="status active">{c}</span>:c}</td>)}</tr>)}</tbody></table></div>;
}

function CheckInPage({ scanState, startScan, confirmCheckin, checkins, inside, openModal }) {
  return <div className="grid checkin-layout"><div className="card scan-card">{scanState==="idle"&&<><div className="scan-tabs"><button className="btn primary"><QrCode/> Scan QR code</button><button className="btn"><ScanLine/> Member ID</button><button className="btn"><UserRoundSearch/> Search member</button></div><div className="scan-frame"><QrCode size={82} color="var(--muted)"/></div><h2>Ready to check in</h2><p>Position the member QR code inside the frame or use another lookup option.</p><button className="btn primary" onClick={startScan}><ScanLine/> Scan demo QR</button></>}{scanState==="scanning"&&<><div className="scan-frame"><QrCode size={82} color="var(--muted)"/><span className="scan-line"/></div><h2>Reading membership…</h2><p>Verifying member status and access.</p></>}{["found","success"].includes(scanState)&&<div className="scan-result"><div className="scan-result-top"><div className="large-avatar">AT</div><div><h2>Abel Tesfaye</h2><p style={{margin:0}}>Gold / Monthly · <span style={{color:"var(--lime)",fontWeight:800}}>ACTIVE</span></p></div></div><div className="info-list" style={{marginTop:24}}><div><span>Valid until</span><strong>October 9, 2026</strong></div><div><span>Trainer</span><strong>Mahi Tadesse</strong></div><div><span>Last visit</span><strong>Today, 6:42 PM</strong></div><div><span>Member ID</span><strong>AF-1024</strong></div></div>{scanState==="success"?<div className="success-banner"><CheckCircle2 size={18} style={{display:"inline",verticalAlign:"middle",marginRight:8}}/> CHECK IN SUCCESSFUL · {new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</div>:<div className="profile-actions" style={{marginTop:24,justifyContent:"flex-start"}}><button className="btn primary" onClick={confirmCheckin}><CheckCircle2/> Complete check in</button><button className="btn" onClick={()=>openModal("renew","Abel Tesfaye")}>Renew membership</button></div>}</div>}</div>
  <div><SectionHead title="Today's check ins" sub={`${checkins.length} recorded · ${inside} currently inside`}/><div className="table-wrap"><table className="table" style={{minWidth:520}}><thead><tr><th>Member</th><th>Time</th><th>Membership</th><th>Status</th></tr></thead><tbody>{checkins.slice(0,12).map((c,i)=><tr key={`${c.member}-${i}`}><td><MiniPerson name={c.member}/></td><td>{c.time}</td><td>{c.membership}</td><td><span className={`status ${c.status==="Inside"?"active":""}`}>{c.status}</span></td></tr>)}</tbody></table></div></div></div>;
}

function Memberships({ openModal, toast }) { return <><div className="toolbar"><span className="spacer"/><button className="btn primary" onClick={()=>openModal("plan")}><Plus/> Create plan</button></div><div className="grid stats"><Stat label="Most popular plan" value="Monthly" note="286 active subscribers"/><Stat label="Highest revenue plan" value="Premium" note="2.24M ETB lifetime"/><Stat label="Renewal rate" value="78%" note="↑ 4.2% this quarter"/><Stat label="Upcoming expirations" value="27" note="Within the next 7 days" muted/></div><SectionHead title="Membership plans" sub="Pricing, benefits and plan performance"/><div className="grid plan-grid">{plansData.map(p=><div className={`card plan ${p.featured?"featured":""}`} key={p.name}>{p.featured&&<span className="popular">MOST POPULAR</span>}<h3>{p.name}</h3><div className="price">{fmt(p.price)} <small>/ {p.duration}</small></div><ul className="benefits">{p.benefits.map(b=><li key={b}>{b}</li>)}</ul><div className="mini-metrics"><div className="mini-metric"><span>Subscribers</span><strong>{p.subscribers}</strong></div><div className="mini-metric"><span>Revenue</span><strong>{(p.revenue/1000000).toFixed(2)}M ETB</strong></div></div><div className="profile-actions" style={{marginTop:14,justifyContent:"flex-start"}}><button className="btn small" onClick={()=>openModal("edit",p.name)}>Edit plan</button><button className="btn small danger" onClick={()=>toast(`${p.name} plan disabled for new sales`)}>Disable</button></div></div>)}</div><SectionHead title="Expiring soon" sub="27 memberships expire within 7 days"><button className="btn" onClick={()=>toast("Reminder sent to 27 members")}><Send/> Send reminder</button></SectionHead><div className="table-wrap"><table className="table"><thead><tr><th>Member</th><th>Plan</th><th>Expiration</th><th>Balance</th><th/></tr></thead><tbody>{initialMembers.filter(m=>m.status==="Expiring Soon").slice(0,6).map(m=><tr key={m.id}><td><MiniPerson name={m.name} sub={m.id}/></td><td>{m.plan}</td><td>{m.expiry}</td><td>{fmt(m.balance)}</td><td><button className="link" onClick={()=>toast(`Reminder sent to ${m.name}`)}>Send reminder</button></td></tr>)}</tbody></table></div></> }

function Payments({ transactions, openModal }) { const total=transactions.reduce((s,t)=>s+t.amount,0); return <><div className="grid stats"><Stat label="Today's revenue" value={fmt(32450 + Math.max(0,total-187000))} note="28 transactions"/><Stat label="This month" value="684,500 ETB" note="↑ 12.4% vs September"/><Stat label="Outstanding" value="42,800 ETB" note="17 members" muted/><Stat label="Expenses" value="118,400 ETB" note="On budget" muted/><Stat label="Net revenue" value="566,100 ETB" note="82.7% margin"/></div><SectionHead title="Transactions" sub="Membership, training and shop payments"><button className="btn primary" onClick={()=>openModal("payment")}><Plus/> Record payment</button></SectionHead><div className="toolbar"><input className="input" placeholder="Search transactions"/><select className="select"><option>All methods</option><option>Cash</option><option>Telebirr</option><option>Bank Transfer</option></select><button className="btn"><Download/> Export</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Transaction</th><th>Member</th><th>Description</th><th>Amount</th><th>Method</th><th>Date</th><th>Staff</th><th>Status</th></tr></thead><tbody>{transactions.slice(0,13).map(t=><tr key={t.id}><td>{t.id}</td><td>{t.member}</td><td>{t.description}</td><td><strong>{fmt(t.amount)}</strong></td><td>{t.method}</td><td>{t.date}</td><td>{t.staff}</td><td><span className="status paid">Paid</span></td></tr>)}</tbody></table></div><SectionHead title="Expenses" sub="Operating costs recorded this month"><button className="btn" onClick={()=>openModal("expense")}><Plus/> Add expense</button></SectionHead><div className="grid stats">{expenses.slice(0,4).map(e=><div className="card" key={e.id}><div className="label">{e.name}</div><div className="value" style={{fontSize:20}}>{fmt(e.amount)}</div><div className="trend muted">{e.date}</div></div>)}</div></> }

function Trainers({ openModal, toast }) { const [selected,setSelected]=useState(null); return <><div className="toolbar"><input className="input" placeholder="Search trainers"/><span className="spacer"/><button className="btn primary" onClick={()=>openModal("staff")}><Plus/> Add trainer</button></div><div className="grid trainer-grid">{trainers.map(t=><div className="card" key={t.name} onClick={()=>setSelected(t)}><div className="trainer-top"><div className="large-avatar" style={{width:54,height:54,fontSize:16}}>{initials(t.name)}</div><div><h3>{t.name}</h3><div style={{color:"var(--muted)",fontSize:12}}>{t.spec}</div></div></div><div className="trainer-stats"><div><strong>{t.clients}</strong><span>Clients</span></div><div><strong>{t.sessions}</strong><span>Today</span></div><div><strong className="rating"><Star size={11} fill="currentColor"/> {t.rating}</strong><span>Rating</span></div></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className={statusClass(t.status)}>{t.status}</span><button className="link">View profile</button></div></div>)}</div>{selected&&<><SectionHead title={`${selected.name}'s schedule`} sub="Today · Monday, October 5"><button className="btn" onClick={()=>openModal("session",selected.name)}><Plus/> Add session</button></SectionHead><div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Client</th><th>Focus</th><th>Status</th><th/></tr></thead><tbody>{[["08:00","Abel Tesfaye","Strength assessment"],["09:30","Sara Bekele","Cardio plan"],["11:00","Dawit Alemu","Upper body"],["15:00","Ruth Mekonnen","Weight loss"],["17:30","Nahom Girma","Strength"]].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className="status active">Confirmed</span></td><td><button className="link" onClick={()=>toast("Schedule updated")}>Edit</button></td></tr>)}</tbody></table></div></>}</> }

function ClassesPage({ openModal, toast }) { const [selected,setSelected]=useState(null); return <><div className="toolbar"><div className="filters"><button className="filter active">Today</button><button className="filter">This week</button><button className="filter">All classes</button></div><span className="spacer"/><button className="btn primary" onClick={()=>openModal("class")}><Plus/> Create class</button></div><div className="grid class-grid">{classes.map(c=><div className={`card class-card ${c.booked===c.capacity?"full":""}`} key={c.id} onClick={()=>setSelected(c)}><div style={{display:"flex",justifyContent:"space-between"}}><div className="class-time">{c.time}</div>{c.booked===c.capacity&&<span className="status broken">Full</span>}</div><h3>{c.name}</h3><p style={{color:"var(--muted)",fontSize:12}}>{c.instructor} · {c.duration} · {c.room}</p><div className="capacity"><i style={{width:`${c.booked/c.capacity*100}%`}}/></div><div style={{display:"flex",justifyContent:"space-between",fontSize:12}}><span>{c.booked} / {c.capacity} booked</span><button className="link">View attendees</button></div></div>)}</div>{selected&&<><SectionHead title={`${selected.name} attendees`} sub={`${selected.booked} confirmed members`}><button className="btn primary" onClick={()=>openModal("booking",selected.name)}><Plus/> Book member</button></SectionHead><div className="table-wrap"><table className="table"><thead><tr><th>Member</th><th>Booked at</th><th>Status</th><th/></tr></thead><tbody>{initialMembers.slice(0,Math.min(8,selected.booked)).map(m=><tr key={m.id}><td><MiniPerson name={m.name} sub={m.id}/></td><td>Oct 4, 4:22 PM</td><td><span className="status active">Confirmed</span></td><td><button className="link" onClick={()=>toast(`${m.name}'s booking cancelled`)}>Cancel booking</button></td></tr>)}</tbody></table></div></>}</> }

function EquipmentPage({ equipment, setEquipment, openModal, toast }) { const [selected,setSelected]=useState(null); const counts={Operational:equipment.filter(e=>e.status==="Operational").length,Maintenance:equipment.filter(e=>e.status==="Maintenance").length,Broken:equipment.filter(e=>e.status==="Broken").length}; const repair=e=>{setEquipment(x=>x.map(i=>i.id===e.id?{...i,status:"Operational",condition:"Good"}:i));setSelected({...e,status:"Operational",condition:"Good"});toast(`${e.name} marked repaired`)}; return <><div className="grid stats"><Stat label="Total equipment" value={equipment.length} note="Across 4 gym zones" muted/><Stat label="Operational" value={counts.Operational} note="Ready for use"/><Stat label="Under maintenance" value={counts.Maintenance} note="2 technicians assigned" muted/><Stat label="Out of service" value={counts.Broken} note="Replacement review" muted/></div><SectionHead title="Equipment register" sub="Condition and maintenance tracking"><button className="btn" onClick={()=>openModal("issue")}><Plus/> Report issue</button></SectionHead><div className="table-wrap"><table className="table"><thead><tr><th>ID</th><th>Equipment</th><th>Category</th><th>Location</th><th>Condition</th><th>Last maintenance</th><th>Next maintenance</th><th>Status</th><th/></tr></thead><tbody>{equipment.map(e=><tr key={e.id} onClick={()=>setSelected(e)}><td>{e.id}</td><td><strong>{e.name}</strong></td><td>{e.category}</td><td>{e.location}</td><td>{e.condition}</td><td>{e.last}</td><td>{e.next}</td><td><span className={statusClass(e.status)}>{e.status}</span></td><td><button className="link">Details</button></td></tr>)}</tbody></table></div>{selected&&<><SectionHead title={selected.name} sub={`${selected.id} · ${selected.location}`}/><div className="grid detail-grid"><div className="card detail-card"><h3>Equipment information</h3><div className="info-list"><div><span>Purchase date</span><strong>{selected.purchased}</strong></div><div><span>Condition</span><strong>{selected.condition}</strong></div><div><span>Cost</span><strong>148,000 ETB</strong></div><div><span>Technician</span><strong>Assigned</strong></div></div></div><div className="card detail-card"><h3>Reported issue</h3><p style={{color:"var(--muted)"}}>{selected.name==="Treadmill #07"?"Belt slipping during high-speed operation.":"Routine preventive maintenance scheduled."}</p><strong>Reported: October 5, 2026</strong></div><div className="card"><div className="profile-actions" style={{justifyContent:"flex-start"}}><button className="btn" onClick={()=>openModal("issue",selected.name)}>Report issue</button><button className="btn" onClick={()=>toast("Maintenance scheduled")}>Schedule maintenance</button><button className="btn primary" onClick={()=>repair(selected)}>Mark repaired</button></div></div></div></>}</> }

function Inventory({ inventory, setInventory, toast }) { const [cart,setCart]=useState([{...inventory[1],qty:2},{...inventory[0],name:"Protein Shake",price:350,qty:1}]); const [method,setMethod]=useState("Cash"); const total=cart.reduce((s,x)=>s+x.price*x.qty,0); const add=p=>{setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]})}; const change=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(0,x.qty+d)}:x).filter(x=>x.qty)); const checkout=()=>{setInventory(items=>items.map(p=>({...p,stock:Math.max(0,p.stock-(cart.find(c=>c.id===p.id)?.qty||0))})));setCart([]);toast(`Payment successful · ${fmt(total)} via ${method}`)}; return <div className="grid inventory-layout"><div><div className="toolbar"><input className="input" placeholder="Search inventory"/><select className="select"><option>All categories</option><option>Nutrition</option><option>Accessories</option></select><span className="spacer"/><button className="btn"><Plus/> Add product</button></div><div className="grid product-grid">{inventory.map(p=><div className="card product" key={p.id}><div className="product-icon">{p.name[0]}</div><div style={{flex:1}}><strong>{p.name}</strong><div style={{color:"var(--muted)",fontSize:11,marginTop:3}}>{p.category} · {p.stock} in stock</div><div style={{marginTop:6}}><strong>{fmt(p.price)}</strong> {p.stock<=p.min&&<span className="status low" style={{marginLeft:6}}>Low stock</span>}</div></div><button className="btn small" onClick={()=>add(p)}><Plus/></button></div>)}</div></div><div className="card cart"><div className="section-head" style={{margin:0}}><h2>Gym shop</h2><ShoppingCart size={18}/></div><p style={{color:"var(--muted)",fontSize:12}}>Front desk point of sale</p>{cart.length?cart.map(x=><div className="cart-row" key={x.id}><div><strong>{x.name}</strong><div style={{color:"var(--muted)",fontSize:10}}>{fmt(x.price)}</div></div><div className="qty"><button onClick={()=>change(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}>+</button></div><strong>{fmt(x.price*x.qty)}</strong></div>):<Empty text="Cart is empty"/>}<div className="cart-total"><span>Total</span><span>{fmt(total)}</span></div><div className="method">{["Cash","Telebirr","Bank Transfer"].map(m=><button className={method===m?"active":""} onClick={()=>setMethod(m)} key={m}>{m}</button>)}</div><button className="btn primary" style={{width:"100%"}} disabled={!cart.length} onClick={checkout}>Checkout · {fmt(total)}</button></div></div> }

function Reports() { const [range,setRange]=useState("This Month"); const insights=[["Attendance pattern","Attendance drops by 31% on Sundays. Consider a Sunday promotion."],["Renewal opportunity","27 memberships expire within the next 7 days, representing 64,500 ETB."],["Capacity alert","Evening hours between 5 PM and 8 PM are operating above 80% capacity."]]; return <><div className="toolbar"><div className="filters">{["Today","This Week","This Month","Last 3 Months","This Year","Custom"].map(x=><button className={`filter ${range===x?"active":""}`} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div><span className="spacer"/><button className="btn"><Download/> Export report</button></div><div className="grid stats"><Stat label="Revenue" value="684,500 ETB" note="↑ 12.4% growth"/><Stat label="Profit" value="566,100 ETB" note="82.7% net margin"/><Stat label="Avg daily check ins" value="287" note="↑ 9% vs last month"/><Stat label="Renewal rate" value="78%" note="Target 82%"/><Stat label="Peak time" value="5 PM – 8 PM" note="84% floor capacity" muted/><Stat label="Popular plan" value="Monthly" note="42% of members"/><Stat label="Best trainer" value="Mahi Tadesse" note="4.9 rating · 18 clients"/><Stat label="Members at risk" value="32" note="No visit in 14+ days" muted/></div><SectionHead title="Business performance" sub={`${range} · Revenue and attendance`}/><div className="grid report-grid"><div className="card"><div className="label">Revenue vs prior period</div><Bars values={[54,62,68,64,78,83,91]} compare/></div><div className="card"><div className="label">Peak gym hours</div><div className="hours">{[18,24,37,42,36,48,68,86,92,82,57,35].map((v,i)=><div className={`hour ${i>=7&&i<=9?"peak":""}`} key={i}><i style={{height:`${v}%`}}/>{i+10}:00</div>)}</div></div></div><SectionHead title="Owner insights" sub="Actionable observations from gym performance"/><div className="grid insights">{insights.map(i=><div className="card insight" key={i[0]}><strong>{i[0]}</strong><p>{i[1]}</p></div>)}</div><SectionHead title="Report library" sub="Detailed operational reports"/><div className="grid quick">{["Revenue Report","Membership Report","Attendance Report","Member Retention","Expired Memberships","Trainer Performance","Class Performance","Inventory Sales","Expenses","Profit","Equipment Maintenance","Peak Hours"].map(x=><button className="btn" key={x}><ClipboardList/>{x}</button>)}</div></> }

function StaffPage({ openModal, toast }) { const roles=[["Owner","Full access to every module and setting"],["Manager","Members, payments, reports, staff and inventory"],["Receptionist","Members, check in, memberships and payments"],["Trainer","Assigned members, workouts, measurements and schedule"],["Accountant","Payments, expenses and financial reports"]]; return <><div className="toolbar"><span className="spacer"/><button className="btn primary" onClick={()=>openModal("staff")}><Plus/> Add staff member</button></div><div className="grid role-grid">{roles.map(r=><div className="card role-card" key={r[0]}><ShieldCheck color="var(--lime)"/><h3>{r[0]}</h3><p>{r[1]}</p></div>)}</div><SectionHead title="Staff directory" sub="Account status and role access"/><div className="table-wrap"><table className="table"><thead><tr><th>Staff member</th><th>Role</th><th>Phone</th><th>Last active</th><th>Status</th><th/></tr></thead><tbody>{staff.map(s=><tr key={s.id}><td><MiniPerson name={s.name} sub={`ST-${100+s.id}`}/></td><td>{s.role}</td><td>{s.phone}</td><td>{s.id%2?"Today, 6:40 PM":"Yesterday"}</td><td><span className={statusClass(s.status)}>{s.status}</span></td><td><button className="link" onClick={()=>openModal("edit",s.name)}>Edit</button></td></tr>)}</tbody></table></div></> }

function SettingsPage({ reset, toast }) { const [section,setSection]=useState("Gym Profile"); const [toggles,setToggles]=useState({expiry:true,stock:true,payment:true,auto:true}); const nav=["Gym Profile","Membership Settings","Check In Settings","Payment Methods","Notification Settings","Staff Roles","Receipt Settings","Theme Preferences"]; return <div className="grid settings"><div className="card settings-nav">{nav.map(n=><button className={section===n?"active":""} onClick={()=>setSection(n)} key={n}>{n}</button>)}</div><div className="card"><SectionHead title={section} sub="Configuration is saved locally for this demo"/>{section==="Gym Profile"?<div className="form-grid"><Field label="Gym name"><input className="input" defaultValue="Abyssinia Fitness Club"/></Field><Field label="Phone"><input className="input" defaultValue="+251 11 662 4080"/></Field><Field label="Email"><input className="input" defaultValue="hello@abyssiniafitness.et"/></Field><Field label="Address"><input className="input" defaultValue="Bole, Addis Ababa, Ethiopia"/></Field><Field label="Opening time"><input className="input" type="time" defaultValue="05:30"/></Field><Field label="Closing time"><input className="input" type="time" defaultValue="22:00"/></Field><Field label="Currency"><select className="select"><option>ETB — Ethiopian Birr</option></select></Field></div>:<div>{["Membership expiry reminders","Low stock alerts","Payment confirmation receipts","Automatic attendance summaries"].map((x,i)=>{const k=Object.keys(toggles)[i];return <div className="toggle-row" key={x}><div><strong>{x}</strong><div style={{color:"var(--muted)",fontSize:11,marginTop:4}}>Enable this preference for staff and management.</div></div><button className={`switch ${toggles[k]?"on":""}`} onClick={()=>setToggles(v=>({...v,[k]:!v[k]}))}/></div>})}</div>}<div className="modal-foot" style={{padding:"20px 0 0",marginTop:20}}><button className="btn danger" onClick={reset}><RotateCcw/> Reset demo data</button><button className="btn primary" onClick={()=>toast("Settings saved")}><Save/> Save settings</button></div></div></div> }

export default function Home() {
  const [page,setPage]=useState("dashboard"),[collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[modal,setModal]=useState(null),[toastMsg,setToastMsg]=useState(""),[showNotifs,setShowNotifs]=useState(false),[selectedMember,setSelectedMember]=useState(null),[scanState,setScanState]=useState("idle");
  const [members,setMembers]=useState(initialMembers),[equipment,setEquipment]=useState(initialEquipment),[inventory,setInventory]=useState(initialInventory),[transactions,setTransactions]=useState(initialTransactions),[checkins,setCheckins]=useState(initialCheckins),[inside,setInside]=useState(83),[notifs,setNotifs]=useState(notificationSeed);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("abyssinia-gym-demo")||"null");if(saved){setMembers(saved.members||initialMembers);setEquipment(saved.equipment||initialEquipment);setInventory(saved.inventory||initialInventory);setTransactions(saved.transactions||initialTransactions);setCheckins(saved.checkins||initialCheckins);setInside(saved.inside||83)}}catch{} const hash=location.hash.slice(1);if(titles[hash])setPage(hash);},[]);
  useEffect(()=>{localStorage.setItem("abyssinia-gym-demo",JSON.stringify({members,equipment,inventory,transactions,checkins,inside}))},[members,equipment,inventory,transactions,checkins,inside]);
  useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:"navigate_gym_module",title:"Open gym module",description:"Open a named module in the gym ERP dashboard.",inputSchema:{type:"object",properties:{module:{type:"string",enum:Object.keys(titles)}},required:["module"],additionalProperties:false},annotations:{readOnlyHint:true},execute:({module})=>{go(module);return{module}}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
  const notify=msg=>{setToastMsg(msg);setTimeout(()=>setToastMsg(""),2800)};
  const go=p=>{setPage(p);setSelectedMember(null);setMobile(false);location.hash=p;window.scrollTo(0,0)};
  const openModal=(type,member)=>setModal({type,member,subject:member});
  const addMember=d=>{const name=`${d.first} ${d.last}`;setMembers(m=>[{id:`AF-${1060+m.length}`,name,phone:d.phone,email:d.email||"—",plan:d.plan,trainer:d.trainer,join:d.start,expiry:"2026-11-05",status:"Active",lastVisit:"Not yet",gender:d.gender,dob:d.dob,emergency:d.emergency,weight:+d.weight||0,height:+d.height||0,goal:d.goal,visits:0,monthVisits:0,balance:0},...m]);setModal(null);notify(`${name} registered successfully`)};
  const recordPayment=d=>{setTransactions(t=>[{id:`TX-${93000+t.length}`,member:d.member,description:d.description,amount:+d.amount,method:d.method,date:"2026-10-05",staff:"Selam A.",status:"Paid"},...t]);setModal(null);notify(`Payment of ${fmt(d.amount)} recorded`)};
  const renew=d=>{setMembers(m=>m.map(x=>x.name===d.member?{...x,plan:d.plan,status:"Active",expiry:"2026-11-05",balance:0}:x));setSelectedMember(s=>s?.name===d.member?{...s,plan:d.plan,status:"Active",expiry:"2026-11-05",balance:0}:s);setTransactions(t=>[{id:`TX-${93000+t.length}`,member:d.member,description:`${d.plan} Membership Renewal`,amount:+d.amount,method:d.method,date:"2026-10-05",staff:"Selam A.",status:"Paid"},...t]);setModal(null);notify(`${d.member}'s membership renewed successfully`)};
  const generic=label=>{setModal(null);notify(`${label} saved successfully`)};
  const startScan=()=>{setScanState("scanning");setTimeout(()=>setScanState("found"),1100)};
  const confirmCheckin=()=>{setScanState("success");setInside(n=>n+1);setCheckins(c=>[{member:"Abel Tesfaye",time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),membership:"Gold / Monthly",status:"Inside"},...c]);notify("Abel Tesfaye checked in successfully")};
  const checkinMember=m=>{go("checkin");setScanState(m.name==="Abel Tesfaye"?"found":"success")};
  const reset=()=>{setMembers(initialMembers);setEquipment(initialEquipment);setInventory(initialInventory);setTransactions(initialTransactions);setCheckins(initialCheckins);setInside(83);localStorage.removeItem("abyssinia-gym-demo");notify("Demo data reset to original values")};
  const unread=notifs.filter(n=>!n.read).length;
  let view;
  if(selectedMember)view=<MemberProfile member={selectedMember} back={()=>setSelectedMember(null)} openModal={openModal} checkinMember={checkinMember}/>;
  else if(page==="dashboard")view=<Dashboard inside={inside} openModal={openModal} go={go}/>;
  else if(page==="members")view=<MembersPage members={members} openMember={setSelectedMember} openModal={openModal}/>;
  else if(page==="checkin")view=<CheckInPage scanState={scanState} startScan={startScan} confirmCheckin={confirmCheckin} checkins={checkins} inside={inside} openModal={openModal}/>;
  else if(page==="memberships")view=<Memberships openModal={openModal} toast={notify}/>;
  else if(page==="payments")view=<Payments transactions={transactions} openModal={openModal}/>;
  else if(page==="trainers")view=<Trainers openModal={openModal} toast={notify}/>;
  else if(page==="classes")view=<ClassesPage openModal={openModal} toast={notify}/>;
  else if(page==="equipment")view=<EquipmentPage equipment={equipment} setEquipment={setEquipment} openModal={openModal} toast={notify}/>;
  else if(page==="inventory")view=<Inventory inventory={inventory} setInventory={setInventory} toast={notify}/>;
  else if(page==="reports")view=<Reports/>;
  else if(page==="staff")view=<StaffPage openModal={openModal} toast={notify}/>;
  else view=<SettingsPage reset={reset} toast={notify}/>;
  return <div className={`app ${collapsed?"collapsed":""}`}><aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><div className="mark">A</div><div className="brand-copy"><strong>Abyssinia Fitness</strong><small>Operations ERP</small></div><button className="collapse" onClick={()=>setCollapsed(true)}><ChevronLeft size={17}/></button></div><nav className="nav">{navItems.map(([id,label,Icon])=><button className={page===id&&!selectedMember?"active":""} onClick={()=>go(id)} key={id} title={label}><Icon/><span>{label}</span></button>)}</nav><div className="sidefoot"><div className="profile"><div className="avatar">SD</div><div className="profile-copy"><strong>Selamawit Desta</strong><small>Owner</small></div><button className="logout" title="Log out" onClick={()=>notify("Demo session remains active")}><LogOut size={16}/></button></div></div></aside><main className="main"><header className="topbar"><button className="iconbtn mobile-menu" onClick={()=>setMobile(!mobile)}><Menu/></button>{collapsed&&<button className="iconbtn" onClick={()=>setCollapsed(false)}><Menu/></button>}<div className="page-title"><h1>{selectedMember?selectedMember.name:titles[page]}</h1><span>{selectedMember?"Member profile":page==="dashboard"?"Monday, October 5, 2026":"Abyssinia Fitness Club"}</span></div><div className="searchbox"><Search/><input placeholder="Search members, payments, equipment…" onKeyDown={e=>{if(e.key==="Enter"){go("members");notify(`Showing results for “${e.currentTarget.value}”`)}}}/></div><span className="demo">● DEMO MODE</span><span className="topmeta">Oct 5, 2026 · 7:18 PM</span><button className="iconbtn" onClick={()=>setShowNotifs(!showNotifs)}><Bell size={18}/>{unread>0&&<span className="count">{unread}</span>}</button><div className="avatar">SD</div></header><div className="content">{view}</div></main>{showNotifs&&<div className="card notifications-pop"><div className="notif-head"><strong>Notifications</strong><button className="link" onClick={()=>setNotifs(n=>n.map(x=>({...x,read:true})))}>Mark all read</button></div><div className="notif-list">{notifs.map(n=><div className={`notif ${!n.read?"unread":""}`} key={n.id} onClick={()=>setNotifs(x=>x.map(y=>y.id===n.id?{...y,read:true}:y))}><span className="notif-dot" style={{opacity:n.read?0:1}}/><div><h4>{n.title}</h4><p>{n.area}</p></div><time>{n.time}</time></div>)}</div></div>}<Modal modal={modal} close={()=>setModal(null)} members={members} onAddMember={addMember} onPayment={recordPayment} onRenew={renew} onGeneric={generic}/>{toastMsg&&<div className="toast"><CheckCircle2 size={17} style={{verticalAlign:"middle",marginRight:8,display:"inline"}}/>{toastMsg}</div>}</div>;
}
